### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by antonkomarev** [nizsheanez/yii2-websocket-application#1]
Could you provide any basic documentation or examples for your library please?

**Comment by nizsheanez** [comment]
Hi, I don't suggest use it in

**Comment by nizsheanez** [comment]
Hi, I don't suggest use this com

**Comment by nizsheanez** [comment]
Hi, I don't recommend to use this component in production, better just go to daemon.io and read documentation abbot ws usage.
